name: Build
on:
  push:
    branches: [dev, main]
  pull_request:
    branches: [dev, main]
  workflow_dispatch:

jobs:
  build:
    name: "${{matrix.title}}"
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        include:
          - {
              title: "Windows x64",
              os: "windows-latest",
              cc: "vs2022",
              arch: "x64",
              build_type: "Release",
            }
          - {
              title: "macOS ARM64",
              os: "macos-latest",
              cc: "clang",
              arch: "arm64",
              build_type: "Release",
            }
          - {
              title: "Linux x64 GCC (Ubuntu 22.04 - Node Only)",
              os: "ubuntu-22.04",
              cc: "gcc",
              arch: "x64",
              build_type: "Release",
              system_qt: true,
              minimal_qt: true,
              node_only: true,
            }
          - {
              title: "Linux x64 GCC",
              os: "ubuntu-24.04",
              cc: "gcc",
              arch: "x64",
              build_type: "Release",
            }
          - {
              title: "Linux x64 Clang",
              os: "ubuntu-24.04",
              cc: "clang",
              arch: "x64",
              build_type: "Release",
            }
          - {
              title: "Linux ARM64 GCC (Ubuntu 22.04 - Node Only)",
              os: "ubuntu-22.04-arm",
              cc: "gcc",
              arch: "arm64",
              build_type: "Release",
              system_qt: true,  # Use system Qt packages instead of Qt 6.9.1
              minimal_qt: true,  # Only install qt6-base-dev (no WebEngine)
              node_only: true,  # Build tau5-node only (no GUI)
            }
          - {
              title: "Linux ARM64 GCC",
              os: "ubuntu-24.04-arm",
              cc: "gcc",
              arch: "arm64",
              build_type: "Release",
            }
          - {
              title: "Linux ARM64 Clang",
              os: "ubuntu-24.04-arm",
              cc: "clang",
              arch: "arm64",
              build_type: "Release",
            }

    steps:
      - uses: actions/checkout@v4

      # Install Qt 6 from action (newer Qt)
      - name: Install Qt 6.9.1
        if: matrix.system_qt != true
        uses: jurplel/install-qt-action@v4
        with:
          modules: "qtpositioning qtserialport qtwebchannel qtwebengine qtwebsockets"
          version: "6.9.1"
      
      # Install system Qt 6 packages from Ubuntu repositories
      - name: Install System Qt 6
        if: matrix.system_qt == true && matrix.minimal_qt == true
        run: |
          sudo apt-get update
          # For tau5-node, we only need Qt base (no WebEngine, etc.)
          sudo apt-get install -y \
            qt6-base-dev \
            qt6-base-dev-tools \
            qmake6-bin \
            libgl1-mesa-dev \
            libglu1-mesa-dev
          # Set Qt6_DIR for CMake to find system Qt
          echo "Qt6_DIR=/usr/lib/$(uname -m)-linux-gnu/cmake/Qt6" >> $GITHUB_ENV
          # Set qmake path explicitly for linuxdeploy-plugin-qt (Ubuntu 22.04 uses qmake6)
          echo "QMAKE=/usr/bin/qmake6" >> $GITHUB_ENV
      

      # Install Elixir (all platforms)
      - name: Install Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: "27"
          elixir-version: "1.18.2"

      # Install Linux build dependencies
      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libasound2-dev libevent-dev libminizip-dev alsa-utils
        if: startsWith(matrix.os, 'ubuntu')

      # Build Release - Windows
      - name: Build Release (Windows)
        working-directory: ${{github.workspace}}/bin/win
        shell: cmd
        run: build-release.bat
        if: startsWith(matrix.os, 'windows')

      # Build Release - macOS
      - name: Build Release (macOS)
        working-directory: ${{github.workspace}}/bin/mac
        run: ./build-release.sh
        if: startsWith(matrix.os, 'macos')

      # Build Release - Linux
      - name: Build Release (Linux)
        working-directory: ${{github.workspace}}/bin/linux
        run: |
          if [ "${{ matrix.node_only }}" = "true" ]; then
            ./build-release.sh --node-only
          else
            ./build-release.sh
          fi
        env:
          CC: ${{ matrix.cc }}
          CXX: ${{ matrix.cc == 'clang' && 'clang++' || 'g++' }}
        if: startsWith(matrix.os, 'ubuntu')

      # Install FUSE for AppImage support (Linux)
      - name: Install AppImage dependencies (Linux)
        run: |
          sudo apt-get update && sudo apt-get install -y fuse libfuse2
        if: startsWith(matrix.os, 'ubuntu') && matrix.cc == 'gcc'

      # Build AppImage - Linux using linuxdeploy with Qt plugin
      # Only build once per architecture using GCC for better compatibility
      # linuxdeploy properly handles Qt6 dependencies without the go-appimage issues
      - name: Build AppImage (Linux)
        working-directory: ${{github.workspace}}/bin/linux
        run: |
          if [ "${{ matrix.node_only }}" = "true" ]; then
            # For node-only builds, only create the node AppImage
            ./build-appimage.sh --node-only
          else
            # For full builds, create both node and full AppImages
            ./build-appimage.sh --node-only
            ./build-appimage.sh
          fi
        if: startsWith(matrix.os, 'ubuntu') && matrix.cc == 'gcc'
      
      # Test AppImages can run
      - name: Test AppImages (Linux)
        working-directory: ${{github.workspace}}/release
        run: |
          if [ "${{ matrix.node_only }}" = "true" ]; then
            # For node-only builds, only test tau5-node AppImage
            for appimage in tau5-node-*.AppImage; do
              echo "Testing $appimage..."
              ./"$appimage" --check
            done
          else
            # For full builds, test both AppImages
            # Test tau5-node AppImage
            for appimage in tau5-node-*.AppImage; do
              echo "Testing $appimage..."
              ./"$appimage" --check
            done
            # Test tau5 AppImage  
            for appimage in tau5-*.AppImage; do
              # Skip tau5-node AppImages (already tested above)
              if [[ "$appimage" != tau5-node-* ]]; then
                echo "Testing $appimage..."
                ./"$appimage" --check
              fi
            done
          fi
        if: startsWith(matrix.os, 'ubuntu') && matrix.cc == 'gcc'

      # Server Tests - Windows (both x64 and ARM64)
      - name: BEAM Tests (Windows)
        shell: cmd
        working-directory: ${{github.workspace}}/server
        run: mix test
        if: startsWith(matrix.os, 'windows')

      # Server Tests - macOS
      - name: BEAM Tests (macOS)
        working-directory: ${{github.workspace}}/server
        run: mix test
        if: startsWith(matrix.os, 'macos')

      # Server Tests - Linux (both x64 and ARM64)
      - name: BEAM Tests (Linux)
        working-directory: ${{github.workspace}}/server
        run: mix test
        if: startsWith(matrix.os, 'ubuntu')

      # Release Health Checks
      # The --check flag now understands release builds
      
      - name: Release Health Check (Windows)
        shell: cmd
        working-directory: ${{github.workspace}}
        run: |
          cd release\Tau5-for-Windows-*
          tau5-gui.exe --check
          tau5-node.exe --check
        if: startsWith(matrix.os, 'windows')

      - name: Release Health Check (macOS)
        working-directory: ${{github.workspace}}
        run: |
          cd release/Tau5-for-macOS-*/
          ./Tau5.app/Contents/MacOS/Tau5 --check
          ./Tau5.app/Contents/MacOS/tau5-node --check
        if: startsWith(matrix.os, 'macos')

      - name: Release Health Check (Linux)
        working-directory: ${{github.workspace}}
        run: |
          if [ "${{ matrix.node_only }}" = "true" ]; then
            # For node-only builds, check only tau5-node
            cd release/Tau5-Node-for-Linux-*/
            ./tau5-node --check
          else
            # For full builds, check both binaries
            cd release/Tau5-for-Linux-*/
            ./tau5-gui --check
            ./tau5-node --check
          fi
        if: startsWith(matrix.os, 'ubuntu')

      # Upload AppImages as artifacts (Linux GCC only)
      - name: Upload AppImage Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: appimage-${{ matrix.os }}-${{ matrix.arch }}
          path: |
            release/tau5-*.AppImage
            release/tau5-node-*.AppImage
        if: startsWith(matrix.os, 'ubuntu') && matrix.cc == 'gcc'